flask_app/main/routes.py
from flask import render_template, request, redirect, url_for, flash, Response
from flask import Blueprint
from ..forms import (SearchForm)
from ..models import User, Comments

main = Blueprint("main", __name__)

@main.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for('football.team_results', query=form.search_query.data))

    return render_template('index.html', form = form)

@main.route("/about")
def about():
    return render_template("about.html", title="About")

@main.route("/howitworks")
def how_it_works():
    return render_template("how_it_works.html", title="How It Works")

@main.route('/user/<username>')
def user_detail(username):
    # Create list of reviews done by the specified user
    reviews = Comments.objects(commenter=User.objects(username=username).first())
    return render_template('user_detail.html', username = username, reviews = reviews)

flask_app/users/routes.py
from flask import render_template, request, redirect, url_for, flash, Response
from flask import Blueprint
from flask import session
import pyotp
import qrcode
# import qrcode.image.svg
from io import BytesIO
import base64

# from flask_sqlalchemy import SQLAlchemy

from flask_mongoengine import MongoEngine
from flask_login import LoginManager, current_user, login_user, logout_user, login_required
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename

# stdlib
from datetime import datetime

from .. import app, bcrypt, client
from ..forms import (PlayerReviewForm, RegistrationForm, LoginForm, UpdateUsernameForm)
from ..models import User, Review, load_user
from ..utils import current_time

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed)

        user.save()

        session['new_username'] = user.username

        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route('/qr_code')
def qr_code():
    if 'new_username' not in session:
        return redirect(url_for('main.index'))

    #user = User.query.filter_by(username=session['new_username']).first()
    user = User.objects(username = session['new_username']).first()
    session.pop('new_username')

    uri = pyotp.totp.TOTP(user.otp_secret).provisioning_uri(name=user.username, issuer_name='Fantasy-Football')
    img = qrcode.make(uri, image_factory= qrcode.image.svg.SvgPathImage)
    stream = BytesIO()
    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
    }

    return stream.getvalue(), headers

@users.route('/tfa')
def tfa():
    if 'new_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
    }
    return render_template('tfa.html'), headers

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.objects(username = form.username.data).first()

        if (user is not None and
            bcrypt.check_password_hash(user.password, form.password.data)):
            login_user(user)

            return redirect(url_for('users.account'))


    return render_template('login.html', title = 'Login', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUsernameForm()

    if form.validate_on_submit():
        # update username field in db

        current_user.modify(username=form.username.data)
        current_user.save()

        return redirect(url_for('users.account'))

    return render_template('account.html', form=form)

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}
    <h1>About Our App</h1>
    <h2>This APP is developed by Pradyumn Bangera and Siddhesh Gupta as part of final project for CMSC388J at University of Maryland</h2>
    <p></p>
       This is an application that was created using Python and Flask. The application includes an account based user
    interaction system. Users can go around the application and view statistics and information about any players From
    the provided NFL teams in our database. Users also have the option to comment about any player, and provide more information
     such as whether they plan to play this player again or how much they would rate the player. This is specifically done so that other
      users can get a better idea when they plan to make similar decisions. Users also have additional accessibility to their own interactions.
      For instance they can view all the comments they have made in the past and even change their usernames if need be. The application provides deep detail on
      every player and their performance throughout different seasons.
      <p></p>
      Disclaimer: The free version of the API provides access to only a certain number of teams and only those teams have been added
 to the group of choices. Often you might come across players that lack any statistical information, and this is because they haven't played during
 the respective season. 
    
    <p></p>
        Created by Pradyumn Bangera and Siddhesh Gupta
    <a href="{{ url_for('main.index') }}">Back</a>
{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}

{% if form.username.errors %}
    <div class="alert alert-warning" role="alert">
        {% for error in form.username.errors %}
            <span>{{ error }}</span>
        {% endfor %}
    </div>
{% endif %}


<div class="row">
    <div class="col">
        {# Greeting #}
        Hi {{ current_user.username }}!
    </div>
</div>
<div class="row">
    <div class="col">
        {# Username Update Form #}

        <div class="row">
          <div class="col">
            <form method="POST" action="">
              {{ form.csrf_token }}
              <div class="form-group">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}

              </div>
              {{ form.submit() }}
            </form>
          </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col">
        Click the link to see all of your reviews!
        <a href="{{ url_for('main.user_detail', username=current_user.username)}}">
            <p><strong>All Reviews</strong></p>
            <a href="{{ url_for('main.index') }}">Back</a>
        </a>
    </div>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Fantasy Football Commentary</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Fantasy Football</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    My Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.about') }}">
                    About
                </a>
            </li>
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}

{% block content %}
<div class="row" style="padding-top: 10%;">
    <div class="col">
        <h2>Welcome To Fantasy Football Statistics!</h2>
        <p></p>
        Please select a team name to get detailed information on every player!
        <p>
        </p>
        As of now, we have information on these select teams!
    </div>
    <div class="col">
        <form method="POST" action="">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.search_query.label }}
                {{ form.search_query(class="form-control") }}

            </div>
            {{ form.submit() }}
        </form>
    </div>


</div>


{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}

{% if form.username.errors %}
    <div class="alert alert-warning" role="alert">
        {% for error in form.username.errors %}
            <span>{{ error }}</span>
        {% endfor %}
    </div>
{% endif %}

<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        You can <a href="{{ url_for('users.register') }}">Register</a> here!
    </div>
</div>
<div class="row">
    <div class="col">
    <form method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group">
        {{ form.username.label }}
        {{ form.username(class="form-control") }}

        {{ form.password.label }}
        {{ form.password(class="form-control") }}

        </div>
        {{ form.submit() }}
    </form>
    </div>
</div>
<a href="{{ url_for('main.index') }}">Back</a>
{% endblock %}

flask_app/templates/player_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<p><b>Error Message: {{ error_msg.message }}</b></p>
<p><b>Status Code: {{ error_msg.status_code }}</b></p>
{% endif %}

{% if player %}

<div class="card-header">
  <h2>{{ player.fullname }} ({{ player.cteam }} #{{player.jnum}})</h2>

</div>
<p>
<div class="row" style="margin-bottom: 60px;">
  <div class="col-sm-3">
    <div class="pricing box-shadow hover-up pricing--best" id="playerOneBox" style="background:#ffffff; border-radius:20px; padding: 40px; border: 4px salmon solid;">
      <div><b>DOB:</b> {{ player.dob }}</div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="pricing box-shadow hover-up pricing--best" id="playerOneBox" style="background:#ffffff; border-radius:20px; padding: 28px; border: 4px salmon solid;">
      <div><b>Height (Inches), :</b> {{ player.height }}</div>
      <div><b>Weight (LBs):</b> {{ player.weight }}</div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="pricing box-shadow hover-up pricing--best" id="playerOneBox" style="background:#ffffff; border-radius:20px; padding: 40px; border: 4px salmon solid;">
      <div><b>Position:</b> {{ player.posd}}</div>
    </div>

  </div>
  <div class="col-sm-3">
    <div class="pricing box-shadow hover-up pricing--best" id="playerOneBox" style="background:#ffffff; border-radius:20px; padding: 40px; border: 4px salmon solid;">
      <div><b>College:</b> {{ player.col }}</div>
  </div>
</div>

<p></p>

  <div class="col">
      <div class="card-body" style="background:#ffffff; border-radius:20px; padding: 40px; border: 4px salmon solid; margin-top: 50px;">
        
        
          {% if player.type == 1 %}
            {% for game in player.oStyle %}
              <div class="row">
                <h2> Season: {{ game.year }} </h2>
                <div class="col-sm-4">
                  <br>
                  Week Number: {{ game.game }}
                  <br>
                  Team: {{ game.team }}
                  <br>
                  Game ID: {{ game.gid }}
                  <br>
                  Pass Attempts: {{ game.pa }}
                  <br>
                  Completions: {{ game.pc }}
                  <br>
                  Pass Yards: {{ game.py }}
                  <br>
                  Interceptions: {{ game.ints }}
                  <br>
                  Passing Touchdowns: {{ game.tdp }}
                  <br>
                  Rushing Attempts: {{ game.ra }}
                  <br>
                  Successful Rushing Attempts: {{ game.sra }}
                  <br>
                  Rush Yards: {{ game.ry }}
                  <br>
                  Rushing Touchdowns: {{ game.tdr }}
                  <br>
                </div>
                <p></p>
                <div class="col-sm-4 ">
                  <p></p>
                  Targets: {{ game.trg }}
                  <br>
                  Receptions: {{ game.rec }}
                  <br>
                  Receiving Yards: {{ game.recy }}
                  <br>
                  Receiving Touchdowns: {{ game.tdrec }}
                  <br>
                  Punt/Kickoff Returns: {{ game.ret }}
                  <br>
                  Return Yardage: {{ game.rety }}
                  <br>
                  Return Touchdowns: {{ game.tdret }}
                  <br>
                  Fumbles Lost: {{ game.fuml }}
                  <br>
                  Penalty Yardage: {{ game.peny }}
                  <br>
                  Snaps: {{ game.snp }}
                  <br>
                  NFL.com Fantasy Points: {{ game.fp }}
                  <br>
                  Fan Duel Fantasy Points: {{ game.fp2 }}
                  <br>
                  Draft Kings Fantasy Points: {{ game.fp3 }}
                  <br>
                </div>
                </div>
                <hr>
                <p></p>
              {% endfor %}
          {% endif %}
          {% if player.type == 2 %}
          {% for game in player.dStyle %}
          <div class="row">
            <h2> Season: {{ game.year }} </h2>
            <div class="col-sm-4">
              <br>
              Week Number: {{ game.game }}
              <br>
              Team: {{ game.team }}
              <br>
              Game ID: {{ game.gid }}
              <br>
              Solo Tackles: {{ game.solo }}
              <br>
              Combined Tackles: {{ game.comb }}
              <br>
              Sacks: {{ game.sck }}
              <br>
              Safeties: {{ game.saf }}
              <br>
              Blocks: {{ game.blk }}
              <br>
              Interceptions: {{ game.ints }}
              <br>
              Passes Defended: {{ game.pdef }}
              <br>
              Fumbles recovered: {{ game.frcv }}
              <br>
              Fumbles Forced: {{ game.forc }}
              <br>
            </div>
            <p></p>
            <div class="col-sm-4 ">
              <p></p>
              Defensive Touchdowns: {{ game.tdd }}
              <br>
              Return Yardage: {{ game.rety }}
              <br>
              Return TDs: {{ game.tdret }}
              <br>
              Penalty Yardage: {{ game.peny }}
              <br>
              Snaps: {{ game.ret }}
              <br>
              NFL.com Fantasy Points: {{ game.snp }}
              <br>
              Fan Duel Fantasy Points: {{ game.fp }}
              <br>
              Draft Kings Fantasy Points: {{ game.fp2 }}
              <br>
            </div>
            </div>
            <hr>
            <p></p>
          {% endfor %}
          {% endif %}
        
      </div>
    <!-- </div> -->
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2> What People Think About This Player <small class="float-right">{{ reviews.count() }} comments</small></h2>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('main.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <br> {{ review.content }}
          <br> <b>Draft Round</b> {{review.draftRound}}
          <br> <b>Rating</b> {{review.rating}}
          <br> <b>Play again?</b> {{review.playAgain}}
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# player review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

        {{ form.draftRound.label }}
        {{ form.draftRound(class="form-control") }}

        {% if form.draftRound.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.draftRound.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

        {{ form.rating.label }}
        {{ form.rating(class="form-control") }}

        {% if form.rating.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.playAgain.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}


        {{ form.playAgain.label }}
        {{ form.playAgain(class="form-control") }}

        {% if form.playAgain.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.playAgain.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
<a href="{{ url_for('main.index') }}">Back</a>
{% endblock content %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p><b>Error Message: {{ error_msg.message }}</b></p>
    <p><b>Status Code: {{ error_msg.status_code }}</b></p>
{% endif %}

<div class="container">
    <h2>Here are you search results:</h2>
    <p></p>
    {% for r in results %}
    <div>
        <h6>
            <a href="{{ url_for('football.player_detail', player_id=r.player_id) }}">
                {{ r.fullname }}
            </a> 
            Position: {{ r.pos1 }} |
            Shirt Number:{{ r.jnum }} | From: {{ r.col }}
        </h6>
        <hr>
        <p></p>
    </div>
    {% endfor %}
</div>
<a href="{{ url_for('main.index') }}">Back</a>
{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}

{% if form.username.errors %}
    <div class="alert alert-warning" role="alert">
        {% for error in form.username.errors %}
            <span>{{ error }}</span>
        {% endfor %}
    </div>
{% endif %}

<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Ask the user to login if they already have an account #}
        If you have an account already, just <a href="{{ url_for('users.login')}}"> log in!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        {# Registration form rendered with Bootstrap #}
        <div class="row">
          <div class="col">
            <form method="POST" action="">
              {{ form.csrf_token }}
              <div class="form-group">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}

                {{ form.email.label }}
                {{ form.email(class="form-control") }}

                {{ form.password.label }}
                {{ form.password(class="form-control") }}

                {{ form.confirm_password.label }}
                {{ form.confirm_password(class="form-control") }}

              </div>
              {{ form.submit() }}
            </form>
          </div>
        </div>

    </div>
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {# Display any error messages #}
    </div>
</div>
<div class="row">
    <div class="col">
        {# Show all reviews made by the user #}

		<div class="row">
			<div class="col-md-12">
			  <h1> Reviews <small class="float-right">{{ reviews.count() }} reviews</small></h1>
			  <ul class="media-list">
				{% for review in reviews %}
				<li class="media review-item">
				  <div class="media-body">
					<span class="float-right">
					  <small>{{ review.date }}</small>
					</span>
					<a href="{{ url_for('football.player_detail', player_id=review.player_id) }}">
					  <strong>@{{ review.player_name }}</strong>
					</a>
					  <br> {{ review.content }}
					  <br> <b>Draft Round</b> {{review.draftRound}}
					  <br> <b>Play again?</b> {{review.playAgain}}
				  </div>
				</li>
				{% endfor %}
			  </ul>
			</div>
		  </div>

    </div>
</div>
{% endblock %}